server:
  port: 8084

spring:
  application:
    name: product


eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
